spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/poc-db
    username: poc
    password: poc
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  liquibase:
    enabled: false