spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/poc-db
    username: poc
    password: poc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect